version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: frontend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    container_name: backend

  database:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    container_name: mongo

  cache:
    image: redis
    container_name: redis

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    container_name: nginx-proxy

volumes:
  mongodb_data:

